### ISSUE TITLE
GPU targeting

### ISSUE THREAD

**Issue by pccross** [cj-mills/Basic-In-Game-Style-Transfer-Tutorial#1]
Hello!  Was wondering if it's possible to target a different GPU with this if I have a system with multiple GPU's, or for some reason I wanted to target the integrated GPU vs. discrete GPU?   
Also, wanted to discuss possibility of extending this project for an article I'm creating, so feel free to reach out to me to discuss.  Thanks!

**Comment by cj-mills** [comment]
@pccross Hi! I believe you can set which GPU runs Unity, but I don't have any experience doing so myself. You can typically set which applications use an Nvidia GPU in the Nvidia Control Panel. There also seems to be a [command line argument](https://docs.unity3d.com/Manual/CommandLineArguments.html), , `-force-device-index`, for specifying a GPU on macOS. However, I don't have a Mac to test that myself.

If you are interested in in-game style transfer specifically, I would recommend checking out my [second tutorial](https://christianjmills.com/End-To-End-In-Game-Style-Transfer-Tutorial-1/) instead. Both the model and method I use in this first attempt are rather inefficient.

It's finals week right now so I don't have much free time, but I can try to assist more next week if needed.

**Comment by pccross** [comment]
Thanks, Christian!  I took a look at the 2nd tutorial, and it's quite nice.
Please email me when your finals are complete, as I'd like to discuss using
variations of this for upcoming technology my company is working on.

**Comment by cj-mills** [comment]
@pccross I have finished with my finals and am free to talk pretty much any time this week. You can reach me at at christian@christianjmills.com
